trash-cli: fix unnecessary typing dependency (#1418)
This package is part of Python's standard library since version 3.5.
Adding it as an explicit depedency causes pip check to report error and
breaks firefox build with such message:

```
8< snip snip snip 8<

trash-cli 0.23.2.13.2 requires typing, which is not installed.

8< snip snip snip 8<

Running "pip check" to verify compatibility between the system Python
and the "mach" site.

8< snip snip snip 8<

Exception: According to "pip check", the current Python environment
has package-compatibility issues.
```

- [x] I am the maintainer of this package.

Co-authored-by: Aelspire <aelspire@gmail.com>
Reviewed-on: https://codeberg.org/kiss-community/community/pulls/1418
Co-authored-by: Aelspire <aelspire@noreply.codeberg.org>
Co-committed-by: Aelspire <aelspire@noreply.codeberg.org>